# SPDX-License-Identifier: GPL-2.0

blksnap-y := 		\
	cbt_map.o	\
	chunk.o		\
	ctrl.o		\
	diff_io.o	\
	diff_area.o	\
	diff_buffer.o	\
	diff_storage.o	\
	event_queue.o	\
	main.o		\
	snapimage.o	\
	snapshot.o	\
	sysfs.o		\
	tracker.o

obj-$(CONFIG_BLK_SNAP)	 += blksnap.o
